# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c306b5ff44c38a8eb8abf2357501072e428be40b40ff0b2aac2ae0a484b89dcf52d8e34b45d258a590321b295ccbce0c71baa484f13b1d6f88d450a53ffb9b93

test:
  secret_key_base: 4f60618ba19d6d7f82485438fd3581f85da917ac5bc0833ada45967de45f1ae4e797d3c0f3d85fe6e6ce1fecbccd786ccba244a46b1a99ae0903e2c564871a38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
